language: php

php:
    - 7.0
    - 7.1
    - nightly

before_install:
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --colors
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml