language: php

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true

sudo: false

install:
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

before_install:
    - composer install --prefer-source

script:
    - mkdir -p build/logs
    - mkdir -p build/cov
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/coveralls

branches:
    only: master

notifications:
    email:
        on_success: never
        on_failure: always

cache:
    directories:
        - vendor
        - $HOME/.cache/composer